version: "3.8"

services:
  whatsapp_automation:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: whatsapp_automation
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
